### ISSUE TITLE
OAuth login not showing.

### ISSUE THREAD

**Issue by greergan** [jrweb247/oauth-pencilblue#1]
I have have installed this plugin and followed the directions, however the FB login button is not displayed. I am using the 0.4.1 release of PB.

**Comment by jrweb247** [comment]
I have forget to say that I have developed this plugin with portofilo theme set as default template theme, if you dont want to use it you can put ^google_oauth^ and ^facebook_oauth^ markup directly in your templates.

The dependencies are:  

> `<link rel="stylesheet" type="text/css" href="^font_awesome_src^">`
> `<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/4.10.1/bootstrap-social.min.css">`

**Comment by greergan** [comment]
Thank you for the info. I now have an FB button for login.

Might you know the cause of this FB error?
I have the following FB settings:
Facebook client id
Facebook client secret

{
   "error": {
      "message": "Invalid redirect_uri: Given URL is not allowed by the Application configuration",
      "type": "OAuthException",
      "code": 191,
      "fbtrace_id": "HAhuuquGF2B"
   }
}

Thank you for your help.

**Comment by jrweb247** [comment]
I think your FB app is not well configured to allow your domain, check your "app domain" and website site url, they must match your pencilblue website
